#!/usr/bin/perl -w

eval 'exec /usr/bin/perl -w -S $0 ${1+"$@"}' if 0; # not running under some shell

use strict;
use File::Basename;

my $redirect = "tv_grab_zz_sdjson_sqlite";

my($filename, $dirs, $suffix) = fileparse("$0");

print (STDERR "This module has been renamed to $redirect.  Please update your usage.\n");
print (STDERR "Attempting to automatically redirect to $redirect\n");

exec "$dirs$redirect$suffix --config-file ~/.xmltv/tv_grab_na_sd.conf @ARGV";
